server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduate_project?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "030927"
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    org.example.dams: DEBUG
    org.example.dams.mapper: DEBUG
  file:
    name: logs/dams.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto